export { default as EighthPareSvg } from './EighthPareSvg'
export { default as FifthPareSvg } from './FifthPareSvg'
export { default as FirstPareSvg } from './FirstPareSvg'
export { default as FourthPareSvg } from './FourthPareSvg'
export { default as SecondPareSvg } from './SecondPareSvg'
export { default as SeventhPareSvg } from './SeventhPareSvg'
export { default as SixthPareSvg } from './SixthPareSvg'
export { default as ThirdPareSvg } from './ThirdPareSvg'
